### PR TITLE
Linux Installation Fest Source and Exported Files

### PR DESCRIPTION
**Pull request by kaygdotorg**

### CODE REVIEW

**Comment by palash25** [comment]
LGTM :+1: 

Just one thing never commit from your master always check out a new branch before sending a PR. Your master should remain clean so that you can work on multiple PRs at the same time. Its a git best practice :wink:

**Comment by palash25** [comment]
Also be sure to follow this guide the next time you make a commit http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html  https://github.com/p-society/meta

**Comment by kaygdotorg** [comment]
Hey! I did read that guide, twice (back when joining PSoC and today morning). I did create a new branch initially but thought a new branch would be very trivial for a presentation repo, which is why I chose to push directly into master; will create a new branch from next time. Sorry for the trouble. :)

**Comment by palash25** [comment]
> but thought a new branch would be very trivial for a presentation repo

quoting from meta **"Every change will be made in a separate branch and PRs are never to be submitted from the master branch. Always keep your master clean"**

> Sorry for the trouble. :)

its ok :smile:

**Pull request merged**
